### ISSUE TITLE
[CWM] Create Swagger spec for MykoMap API

### ISSUE THREAD

**Issue by ms0ur1s** [DigitalCommons/mykomap-monolith#2]
### Description
Based on the API design for MykoMap discussed in [Issue DigitalCommons/mykomap#267](https://github.com/DigitalCommons/mykomap/issues/267) and the  [notes from the meeting on 20/8](https://docs.google.com/document/d/1aguAEMKfr8gqZRVkhJnb46VRJKd5wPMLLOQ1UmAKgFo/), create a Swagger (OpenAPI) specification. This spec will outline the API endpoints, request/response formats, and any necessary validation rules.

### Objectives

- Define the API endpoints as outlined in the meeting notes.
- Specify the HTTP methods (GET, POST, DELETE, etc.) for each endpoint.
- Include request and response schemas, including data models.
- Document error handling and expected status codes.

### Acceptance Criteria

- A complete Swagger spec that covers all discussed API endpoints.
- The spec should be validated and ready for use by the development team.
- Ensure the spec is reviewed and approved by at least one senior developer.

**Comment by wu-lee** [comment]
I suggest we want to add some information about the API on the default route, or perhaps under `about/`

- [http://blah/api/about]() -> `{name: 'Mykomap API', apiVersion: 'v4.0.0:0fdeaf', deployed:'2024-09-02T14:56:04'}` (version is generated using something like `git describe --always --tags --dirty --abbrev=6`)

**Comment by wu-lee** [comment]
> @wu-lee has created a draft API spec here: https://app.swaggerhub.com/apis/SWAGGERHUBWULEE/mykomap/0.1.0


Note this has moved to a DCC account here:

https://app.swaggerhub.com/apis/DigitalCommonsCoop/Mykomap/0.1.0

(Details in BitWarden)
