### ISSUE TITLE
[CWM] Clicking on marker should toggle the pop-up, rather than just open it.

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#43]
**Describe the bug**
When you click on a marker it triggers the opening of the popup. Click again and it opens again. We want the marker to close on a second click.

**To Reproduce**
1. Go to a marker
2. Click on it
3. The marker opens.
4. Click again
5. It stays open, when it should close

**Expected behaviour**
When you click on a marker it triggers the opening of the popup. Click again and it closes.

**Context (please complete the following information):**
 - Device: PC

**Comment by ColmDC** [comment]
Works on deploy-2024-11-19-36-gdf4a89a, on Desktop and mobile
