### ISSUE TITLE
[CWM] Add clear (x) icon to search in Desktop designs

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#44]
## Description
Mobile designs have an (x) to clear search, but desktop designs do not.

Can this be added:
https://xd.adobe.com/view/0f8c7d84-e063-4008-a2fb-c7e3b8580d07-5adf/screen/a3b55da4-cc61-4d0f-8fba-3349aa68449c

## Acceptance Criteria

- (X) to clear search added to desktop designs.

**Comment by rogup** [comment]
Fixed by #42

**Comment by lin-d-hop** [comment]
This is looking fine in the current live versions
