### ISSUE TITLE
[CWM]  Make first north America datasets live on CWM

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#45]
## Description

The north American datasets have already been processed and cleaned by the data factory. These are the first datasets to make live.
[This spreadsheet](https://docs.google.com/spreadsheets/d/1bIVGZ1O56NVURZ9Zw7yDdz2sALTKEWgVxhYwY3hwwfM/edit?gid=0#gid=0) lists all the datasets and their source files

These datasets include:
- NCBA Members
- DotCoop registrants(.coop & marque)
- ICA
- USDA
- NCG
- US Federally Insured Credit Unions
- Farm Credit Administrators

## Acceptance Criteria

- The above datasets are live on the CWM

**Comment by wu-lee** [comment]
A first deployment of "canned" data useable by the current deployment of the CWM is here:

- https://dev.maps.coop/cwm/?datasetId=north-america

As such the search/filtering isn't really working, nor do pop-ups, but the points are visible.

The data us committed to the `cwm-test-data` repo [here]. The CWM currently can't handle location-less entries so those are removed manually after being deployed for the time being.

A update to the back-end will follow.


[here]: https://github.com/DigitalCommons/cwm-test-data/tree/north-america

**Comment by ColmDC** [comment]
>The CWM currently can't handle location-less entries

Does this require  a new ticket?

**Comment by wu-lee** [comment]
I've added a fix on my branch, so this should be fixed in the integrated result.

Ideally though it needs to be reviewed by @rogup however, to check I've not missed something. (Search for "handle nullable Locations in a Dataset")

**Comment by wu-lee** [comment]
This had been updated with a tentative integration of the current work in progress here:

https://dev.maps.coop/cwm/?datasetId=north-america

It now includes partially complete work from issues #20, #29 and #30, PRs #42, #50, #52, #53

I can't speak for #42 and #52, but #52 and #53 related to data definitions in the back-end and #50 to a script to import data, which is nominally working but unreviewed and supplied the data visible in the map. Not everything is plumbed in (popups have dummy content), but searches and filters may be working?

Aside: The code is tagged `deploy-2024-11-12`.  However being on the nick/dev branch that may shift and pull the rug from the tag.

**Comment by wu-lee** [comment]
So this could be construed as done, but it's missing:
- full language support on all vocabs used (notably, data source names, UI labels)
- any review of the data and vocab choices made

I think those should be in other issues however.

**Comment by lin-d-hop** [comment]
CLosing this issue to move the outstanding bits to issues pertaining to translations
