### ISSUE TITLE
[CWM] Add Co-ops UK Open Data to CWM

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#46]
## Description

Add the Coops UK open data to the CWM.
[This spreadsheet](https://docs.google.com/spreadsheets/d/1bIVGZ1O56NVURZ9Zw7yDdz2sALTKEWgVxhYwY3hwwfM/edit?gid=0#gid=0) lists all the datasets and their source files

This will involve:
- normalising the data
- merging and pushing the data to live

## Acceptance Criteria

- Coops UK Open Data is live on the CWM

**Comment by wu-lee** [comment]
This a sub-issue of #54 I think...

**Comment by ColmDC** [comment]
Resolved in deploy-2024-11-19-28-ga2a3fe4
