### ISSUE TITLE
[CWM] Add the Cooperatives Mutuals Canada Federation data to the CWM

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#48]
## Description

Add the Cooperatives Mutuals Canada Federation data to the CWM.
[This spreadsheet](https://docs.google.com/spreadsheets/d/1bIVGZ1O56NVURZ9Zw7yDdz2sALTKEWgVxhYwY3hwwfM/edit?gid=0#gid=0) lists all the datasets and their source files

This will involve:
- normalising the data
- merging the data

## Acceptance Criteria

- Cooperatives Mutuals Canada Federation data is live on the CWM

**Comment by wu-lee** [comment]
This a sub-issue of #54 I think...

**Comment by wu-lee** [comment]
GeoAPIfy geocoded version deployed here: https://dev.data.solidarityeconomy.coop/cmc/
