### ISSUE TITLE
[CWM] Add the US Worker Co-op Federation data to the CWM

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#49]
## Description

Add the US Worker Co-op Federation data to the CWM.
[This spreadsheet](https://docs.google.com/spreadsheets/d/1bIVGZ1O56NVURZ9Zw7yDdz2sALTKEWgVxhYwY3hwwfM/edit?gid=0#gid=0) lists all the datasets and their source files

This will involve:
- normalising the data
- merging the data

## Acceptance Criteria

- US Worker Co-op Federation data is live on the CWM

**Comment by wu-lee** [comment]
A converter has been added for this data in the open-data `dev` branch, under the `usfwc` directory.  The output has been deployed at https://dev.data.solidarityeconomy.coop/usfwc/

**Comment by ColmDC** [comment]
There are 603 co-ops in the data, yet if I filter by US Federation of Worker Coops it states that there are 706 matching results

![Image](https://github.com/user-attachments/assets/b62497c1-e486-4a31-b3be-186df8a6df9e)

**Comment by ColmDC** [comment]
Ignore the fact that the image has the # matching results at 200 in the results panel. I think that is a bug from the pagenation sort cut. See note [here](https://github.com/DigitalCommons/mykomap-monolith/issues/55#issuecomment-2489282730)

**Comment by rogup** [comment]
There are 706 entries in the searchable.json for USFWC... @wu-lee are there the same number of entries in the original csv? where actually is this csv kept?

**Comment by ColmDC** [comment]
> where actually is this csv kept?

https://docs.google.com/spreadsheets/d/1bIVGZ1O56NVURZ9Zw7yDdz2sALTKEWgVxhYwY3hwwfM/edit?gid=0#gid=0

**Comment by rogup** [comment]
@ColmDC I mean the full csv containing all merged data

**Comment by wu-lee** [comment]
It's in https://github.com/DigitalCommons/demo-merge-map-data/, `delhi-data` branch, in a file called `delhi-data.csv`

**Comment by wu-lee** [comment]
I think this will be fixed as soon as I regenerate the data and deploy it.  See https://github.com/DigitalCommons/mykomap/issues/275#issuecomment-2491804895
