### ISSUE TITLE
[CWM]  Add India Data to CWM

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#54]
## Description

Add the India data to the CWM.
[This spreadsheet](https://docs.google.com/spreadsheets/d/1bIVGZ1O56NVURZ9Zw7yDdz2sALTKEWgVxhYwY3hwwfM/edit?gid=0#gid=0) lists all the datasets and their source files

This will involve:
- normalising the data
- merging and pushing the data to live

## Acceptance Criteria

- India Data is live on the CWM

**Comment by ColmDC** [comment]
See https://github.com/DigitalCommons/cwm-test-data/issues/1

**Comment by wu-lee** [comment]
I think all the datasets are now normalised via the datafactory (open-data repo) and deployed on the relevant URL https://dev.data.solidarityeconomy.coop/<dataset tag>/. In general I'll be using the development data versions.

Next step is to perform quick and dirty concatenation without any deduplication of organisations, as discussed. Only three of the new datasets have domains and so can be deduplicated. This data can then be deployed and checked on the CWM map. 

After that I can look at a more scalable "merging" of the datasets using deduplication by .coop and potentially other attributes. If I can see a quick way to do that I will.

**Comment by wu-lee** [comment]
Ok, I've done a slap-dash "merge" of the new datasets CUK, USFWC, CMC and IFFCO, without any de-duplication (although IFFCO, the massive one, has no domain info), converted the data to myko-data  and deployed it on dev-2. Et voila: https://dev.maps.coop/cwm/?datasetId=delhi

The script and the intermediate data will get pushed to `demo-merge-map-data` although I'm likely to review it and possibly tinker with it tomorrow.

**Comment by ColmDC** [comment]
All the required datasets are in. Any deficiencies and co-op-co-op deduplication process can have a seperate issue.
