### ISSUE TITLE
[CWM] Convert backend to Typescript & implement API type safety / validation

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/mykomap-monolith#6]
## Description

Following on from the investigation in https://github.com/DigitalCommons/mykomap/issues/269 , we need to have a go at implementing ts-rest + Zod on the backend.

## Acceptance Criteria

- [x] All back-end source code is in typescript ~and fully typed~ -> Nick to work on this
- [x] We have a typescript ts-rest contract file in the API shared library, that defines our REST API.
- [x] We have a script that can generate an OpenAPI spec from our ts-rest contract
  - [ ] and maybe automatically upload it to SwaggerHub as part of our CI pipeline?
- [x] We have runtime validation of our back-end API routes using Zod
- [x] Changes to the contract are immediately flagged as type errors in the FE/BE without need for a build or code generation.

**Comment by lin-d-hop** [comment]
Delivery 5/9

- [ ] Separate branch to convert backend to Typescript

**Comment by wu-lee** [comment]
Back-end is now typescript, as of e5b84f86450. Initially with `@ts-nocheck` but those are now removed.

The `tsconfig.json` is using `strict`, but I'm not certain how strict the typing is however. I have a feeling we got Mykomap 3.0 to be more strict than this. Will investigate in future work, however.

**Comment by wu-lee** [comment]
@rogup I've just submitted a review request for the branch `ts-restify-the-backend` here: https://github.com/DigitalCommons/mykomap-monolith/pull/15

This should cover the final two points on the list above. (But not including uploading the swagger spec.)

**Comment by wu-lee** [comment]
Merged a while ago, I think this is done, so closing.
