### ISSUE TITLE
[CWM]  Centre map position to marker on click (marker or result)

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#64]
## Description

There is currently no animation that moves the centre of the map to last point the user has clicked on.

This results in some odd behaviour:
- When you click on a search result, the map does not move to centre there. The pop up does open, but if it is off screen you dont see it
- When the marker you click on is toward the edge of the screen the popup appears partially off screen and you have to navigate to it.

From Marcel in Element:
This is the flyTo capability we need when a result is clicked. https://maplibre.org/maplibre-gl-js/docs/examples/flyto/

## Acceptance Criteria

- [x] Clicking on a search result centres the map around the marker for that result.
- [x] Clicking on a marker centres the map around that marker

**Comment by ColmDC** [comment]
Sounds right. @ms0ur1s Is the default Flyto behaviour to end up at the same zoom depth as at the start? Seems appropriate.

**Comment by rogup** [comment]
This is almost ready for QA, just need to fix for mobile tomorrow morning

**Comment by ms0ur1s** [comment]
> This is almost ready for QA, just need to fix for mobile tomorrow morning

💪

**Comment by lin-d-hop** [comment]
@rogup This is looking amazing!!
It makes such a big difference to the usability of the map.
Amazing work!!!

**Comment by ColmDC** [comment]
Works nicely for me on deploy-2024-11-19-19-g90507c4, Firefox, Desktop, and my old Android, Firefox again.

**Comment by lin-d-hop** [comment]
Some issues on mobile - Fairphone 3 on Android/Chrome:

1. Centring is off centre. It aligns with the top. Happy to live with this.
![Image](https://github.com/user-attachments/assets/cad590da-e7d2-40dd-b217-f37acf93031c)


2. When I move around the screen the popup jumps and makes navigating difficult. Not caused by this issue but mentioning for the first time here. @rogup have you experienced this? Shall I create a bug?
In the image I simply moved the map a little and the popup jumped from image above to image below.
![Image](https://github.com/user-attachments/assets/7be533a1-0ca2-4254-9fea-10ca12a245fe)

**Comment by lin-d-hop** [comment]
Thanks @rogup 

1. Happy to leave 1 as is. Nice use of chatgpt 💪 

2. How hard would this be on mobile only? Its fine on desktop but space is so tight on mobile.

**Comment by lin-d-hop** [comment]
> 2.  How hard would this be on mobile only? Its fine on desktop but space is so tight on mobile.

Actually I think this would make sense on mobile and desktop. I'll make an issue

**Comment by ColmDC** [comment]
I wonder if zooming should not hide the popup or trigger a recentre.

**Comment by ColmDC** [comment]
As in https://github.com/DigitalCommons/mykomap-monolith/issues/78#issuecomment-2514276741

closing this ticket and will conduct review of UI behaviour.
