### ISSUE TITLE
[CWM]  URL to Coop does not work

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#65]
**Describe the bug**

In the darker region of the marker popup there is a URL to a coop. This link does not work to click on it.

**To Reproduce**
1. Go to the CWM map
2. Click on a marker
3. Click on the RHS url (see image)
4. Nowt happens

**Expected behaviour**
This looks like a link and thus should open the website in a new tab

**Screenshots/GIFs**

![Image](https://github.com/user-attachments/assets/efd5fef7-089f-435e-b201-32cbbe7b7e51)

**Comment by ColmDC** [comment]
Fix not visible in deploy-2024-11-19-19-g90507c4

Perhaps it's not deployed yet, and preamaturely in QA column

**Comment by ColmDC** [comment]
Now visible in deploy-2024-11-19-22-gcbbd578
