### ISSUE TITLE
[CWM]  Ensure the same tag is used in the filters and the results

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#68]
## Description

In the drop down filters the identifier/tag/name that is used is friendly and human readable.
The same field populated in the popup is given an opaque code.

Can the marker use the same identifier/tag/name that is used in the dropdown filter?

![Image](https://github.com/user-attachments/assets/552785e3-3339-4734-b5a2-494174859b51)

## Acceptance Criteria

- [x] Ensure that a human readable identifier/tag/name is used in the popups

This applies to:
- [x] Primary Activity
- [x] Organisational Structure
- [x] Typology
- [x] Data sources (specifically DotCoop)

**Comment by ColmDC** [comment]
Working in deploy-2024-11-19-22-gcbbd578
