### ISSUE TITLE
[CWM]  Strip/render tags/html from popup descriptions

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#69]
## Description

Many of the descriptions have html tags in them. They contain a mix of special characters, line breaks and paragraph tags mostly.

I need more info to spec this issue well. My initial thoughts are:
- Strip everything in <...> tags
- Render everything in &...; tags

&...; tend to be special characters like Õ or &nbsp;
<...> tend to be <p></p> but may also include <strong> which is more relevant.

One to chat through if we get to it in time so that we can choose the right approach balancing time and impact.

## Acceptance Criteria

- [ ] TBC

**Comment by rogup** [comment]
I'll do a basic strip of tags using a regex replace:
`string.replace(/<[^<>]+(>)/g, "")`

and use https://www.npmjs.com/package/html-entities to decode entities

Maybe best to eventually do this in the data pipeline but I'll just add it to the front-end for now

**Comment by rogup** [comment]
https://github.com/DigitalCommons/mykomap-monolith/commit/5d8d6cec8b7a9d608cdd13de99c17694486348e6

merged

**Comment by wu-lee** [comment]
The way that the old Mykomap did this was to insert the text raw into the pop-up.

This isn't ideal if you don't trust the HTML, which we probably shouldn't, but it strikes me as the easiest most reliable route to seeing what we used to.  Somewhat moot point now, however, if it's been done and merged already.

Later we should decide what we want the descriptions to be, and make sure the data has that - e.g. sanitised HTML

**Comment by ColmDC** [comment]
Not seeing any bad text rendering.
