### ISSUE TITLE
[CWM]  Hide Section Titles if the section is empty

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#70]
## Description

The popup template has placeholder titles for a range of interesting coop information.
However if the section is unpopulated it makes the popup look messy.

Let's hide any section titles if the section is empty.

![Image](https://github.com/user-attachments/assets/7dc2c269-af09-4239-a015-01a887088a6f)

## Acceptance Criteria

- [ ] For any empty sections the section title is not displayed.

**Comment by ColmDC** [comment]
Looking cleaner. deploy-2024-11-19-28-ga2a3fe4
