### ISSUE TITLE
[CWM]  Country list is not displayed in alphabetical order

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#71]
## Description

Country list is not displayed in alphabetical order. This is a problem as our UI design demands a dropdown (instead of allowing users to start typing) meaning that if a country is in an awkward list position it is basically impossible to find.

![Image](https://github.com/user-attachments/assets/11ed7b2b-c0c3-466a-9288-deb0e5a2bd83)

From Colm: They are ordered by ISO_3166-1_alpha-2. Is it straight forward to order alphabetically in each language?

## Acceptance Criteria

- [ ] Display countries in alphabetical order.

**Comment by rogup** [comment]
I'll just sort all filters alphabetically

**Comment by rogup** [comment]
done https://github.com/DigitalCommons/mykomap-monolith/commit/a2a3fe4f34f3723818f39be736026c458b8c5ace

**Comment by ColmDC** [comment]
WOrking in deploy-2024-11-19-28-ga2a3fe4
