### ISSUE TITLE
[CWM]  Close popup on move map

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#78]
## Description

When a popup is opened and the map is moved by the user it creates an experience in which the popup jumps around the map. This is a bit odd on desktop, but on mobile it renders the map very hard to use.

Let's resolve this by closing the popup on moving the map.

A bit more context in #64 

## Acceptance Criteria

- [ ] When a popup is open, if the user moves the map the pop up closes.

**Comment by ColmDC** [comment]
This is how it behaves in deploy-2024-11-19-28-ga2a3fe4

**Comment by rogup** [comment]
@ColmDC I'm not seeing this behaviour anymore on dev.maps.coop
The popup stays in the position directly above the marker, even as the marker moves offscreen

**Comment by ColmDC** [comment]
Yes, @wu-lee disabled the popup repositioning relative to marker, which improved the situation, but not a complete fix. I think the best way forward is to close the current popup tickets and do a review of the popup behaviour on a wide range of devices. Identifying the zoom depths/distance from top/bottom of screen that exhibit the poor behaviour and then fix.
