### ISSUE TITLE
[CWM] Clear Search Button does not clear text from textbox

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap-monolith#81]
**Describe Issue**
Pressing the Clear Search button does not clear the text from the text box.

**Replicate**
 - Run https://dev.maps.coop/cwm/?datasetId=delhi
 - Open search panel and search for _app_
 - See results panel
 - Press Clear Search
 - _app_ is still in the text box 

**Expected behaviour**
The text box should be cleared

**Comment by rogup** [comment]
This is in `dev` https://github.com/DigitalCommons/mykomap-monolith/commit/1101b2224217895a131000ba7bb5ebcb28387599
Ready to be included in the next deploy for QA

Probably worth waiting for https://github.com/DigitalCommons/mykomap-monolith/pull/93 though, so they can be added at the same time

**Comment by ColmDC** [comment]
Working now in deploy-2024-11-24-0-g7ac5e22
