### ISSUE TITLE
[CWM] Minor text issues

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap-monolith#82]
- [x] Change App Title from _React Redux App_ to _Cooperative World Map_
 - [x] Add Logo into a Corner ![Image](https://github.com/user-attachments/assets/93164a23-607f-4f36-aa99-4cc0b2860286) @ms0ur1s can choose where exactly and size
 - [x] Use available translations for _-any-_ in filters 
 - [x] Use translations for _no_location_available_ in Popups. Use  _no_location_data_available_

**Comment by lin-d-hop** [comment]
Is that the CWM logo?
Can we add it as a favicon to the app?

**Comment by ColmDC** [comment]
Some more assets.
![Cooperative World Map Logo (1)](https://github.com/user-attachments/assets/ea9a39df-6a35-402d-a31f-992d5eb3869e)
![Cooperative World Map Logo](https://github.com/user-attachments/assets/89901282-9c2e-40da-a960-d39a38418f3a)
![Cooperative World Map Logo (4)](https://github.com/user-attachments/assets/836355a1-fe51-4a46-8ac4-4932e87edc9a)

**Comment by ms0ur1s** [comment]
> Is that the CWM logo? Can we add it as a favicon to the app?

@lin-d-hop favicon added

**Comment by ColmDC** [comment]
All visible in deploy-2024-11-19-41-g2e5b07b
