### ISSUE TITLE
[CWM] Limit outer Zoom level to avoid multiple versions of the world

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap-monolith#84]
**Description**
Max zoom out level allow us to see continents multiple time.
Set limits on zoom out to avoid this.

**Comment by ColmDC** [comment]
Can you comment on what restrictions you added?

**Comment by rogup** [comment]
Changed minZoom from 1.1 to 1.45 and adjusted the initial map bounds accordingly
