### ISSUE TITLE
[CWM] Deploy production server

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#86]
## Description

Let's get a production server live baby!

If there are any divergences from the documented scripts and workflow we need to make sure they are documented and the team is across them. So this task warrants a methodical approach.

## Acceptance Criteria

- [x]  A prod server live and the URL is shared across the team - share the URL via element and on this issue
- [x] web dev to point to prod (colm to share url with webdev)
- [x] lynne to point uptime kuma to prod
- [ ] ssh public keys for everyone that might need access (dev team + ~~colm~~ and lynne)
- [x] Nick can successfully deploy, restart, and any other potential actions on this server.

**Comment by lin-d-hop** [comment]
I've run out of time today so will add uptime kuma monitoring over the weekend
https://maps.coop/cwm/?datasetId=delhi

**Comment by ColmDC** [comment]
And it is now being used in worldmap.coop

**Comment by ColmDC** [comment]
Can we tick the last 2 of these boxes @wu-lee ?

**Comment by wu-lee** [comment]
I think so yes. I've done a deploy. And I've checked the keys - John, Rohit, Lynne and I are there. @ColmDC, you are not, should you be?

**Comment by ColmDC** [comment]
I haven't needed/generated/used one for ages.
